# Generated by Django 4.2.7 on 2023-12-08 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("isComplete", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField(default=datetime.date.today)),
                (
                    "weight",
                    models.CharField(
                        choices=[("1", "Low"), ("2", "Normal"), ("3", "High")],
                        default="2",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "Note"),
                            ("2", "To do"),
                            ("3", "Event"),
                            ("4", "Holiday"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["isComplete"],
            },
        ),
    ]
